### ISSUE TITLE
Crashing after select text in message and tap somewhere

### ISSUE THREAD

**Issue by ghost** [vit1-irk/idec-mobile#27]
Crash reproducable for me.

Log:
```
USER_COMMENT=
ANDROID_VERSION=6.0
APP_VERSION_NAME=Mon Jan 01 21:49:10 IRKT 2018
BRAND=ASSISTANT
PHONE_MODEL=AS-5432
CUSTOM_DATA={}
STACK_TRACE=java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 335]
	at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
	at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4300)
	at android.widget.Editor$HandleView.updatePosition(Editor.java:3736)
	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2513)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

**Comment by vit1-irk** [comment]
Just tried to migrate to AppCompatTextView (for message text display widget) assuming the bug was fixed there.

Try the latest build. If the problem persists, I'll try something else

**Comment by ghost** [comment]
> If the problem persists

Yes, still reproducable :-(
```
USER_COMMENT=
ANDROID_VERSION=6.0
APP_VERSION_NAME=Sat Jan 13 22:37:01 IRKT 2018
BRAND=ASSISTANT
PHONE_MODEL=AS-5432
CUSTOM_DATA={}
STACK_TRACE=java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 3971]
	at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
	at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4300)
	at android.widget.Editor$HandleView.updatePosition(Editor.java:3736)
	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2513)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by vit1-irk** [comment]
Just now I have copypasted some workarounds from StackOverFlow.
Try new buils, it should work

**Comment by ghost** [comment]
OK, now it work without fails.

Temporary close this issue.
